steps:
- name: maven:3.8.6-openjdk-11-slim
  dir: examples/pipelinedp4j
  entrypoint: mvn
  args: ['clean', 'package']
- name: google/cloud-sdk:slim
  dir: examples/pipelinedp4j
  args:
  - "gcloud"
  - "dataflow"
  - "flex-template"
  - "build"
  - "${_DATAFLOW_TEMAPLATE_BUCKET_NAME}/${_PIPELINE_NAME}/dataflow-flex-template.json"
  - "--image-gcr-path=${_ARTIFACT_REGISTRY_NAME}/${_PIPELINE_NAME}/dataflow-flex-template:latest"
  - "--sdk-language=JAVA"
  - "--flex-template-base-image=JAVA11"
  - "--metadata-file=beam/metadata.json"
  - "--jar=${_JAR}"
  - "--env=FLEX_TEMPLATE_JAVA_MAIN_CLASS=${_FLEX_TEMPLATE_JAVA_MAIN_CLASS}"
  - "--cloud-build-service-account=projects/${PROJECT_ID}/serviceAccounts/${_SERVICE_ACCOUNT}"
  - "--gcs-log-dir=gs://${_DATAFLOW_TEMAPLATE_BUCKET_NAME}/cloudbuild_logs" #custom service account with cloud build requires options.logging: CLOUD_LOGGING_ONLY but gcloud dataflow flex-template build does not support it
substitutions:
  _PIPELINE_NAME: differential-privacy
  _JAR: beam/target/beam-1.0-SNAPSHOT.jar
  _FLEX_TEMPLATE_JAVA_MAIN_CLASS: com.google.privacy.differentialprivacy.pipelinedp4j.examples.BeamExample
options:
  logging: CLOUD_LOGGING_ONLY