steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t ${_ARTIFACT_REGISTRY_NAME}/${_PIPELINE_NAME}/dataproc-template:latest --file ./examples/pipelinedp4j/spark/Dockerfile ./examples/pipelinedp4j/spark
  automapSubstitutions: true
images:
- '${_ARTIFACT_REGISTRY_NAME}/${_PIPELINE_NAME}/dataproc-template:latest'
substitutions:
  _PIPELINE_NAME: differential-privacy
  _ARTIFACT_REGISTRY_NAME: europe-west4-docker.pkg.dev/${PROJECT_ID}/movsic-artifact-registry
  _SERVICE_ACCOUNT: dp-cloudbuild@${PROJECT_ID}.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY