steps:
- name: google/cloud-sdk:slim
  args:
  - "gcloud"
  - "dataproc"
  - "batches"
  - "submit"
  - "spark"
  - "--batch=${_PIPELINE_NAME}-${BUILD_ID}"
  - "--class=${_JAVA_MAIN_CLASS}"
  - "--project=${PROJECT_ID}"
  - "--region=${_LOCATION}"
  - "--service-account=${_SERVICE_ACCOUNT_EMAIL}"
  - "--container-image=${_ARTIFACT_REGISTRY_NAME}/${_PIPELINE_NAME}/dataproc-template:latest"
  - "--"
  - "--inputFilePath=gs://${_INPUT_GCS_PATH}"
  - "--outputFolder=gs://${_OUTPUT_GCS_PATH}"
substitutions:
  _PIPELINE_NAME: differential-privacy
  _ARTIFACT_REGISTRY_NAME: europe-west4-docker.pkg.dev/${PROJECT_ID}/movsic-artifact-registry
  _SERVICE_ACCOUNT_EMAIL: dp-dataproc@${PROJECT_ID}.iam.gserviceaccount.com
  _LOCATION: europe-west4
  _JAVA_MAIN_CLASS: com.google.privacy.differentialprivacy.pipelinedp4j.examples.SparkExample
  _INPUT_GCS_PATH: movsic-dataflow-templates/input/netflix_data.csv
  _OUTPUT_GCS_PATH: movsic-dataflow-templates/output
options:
  logging: CLOUD_LOGGING_ONLY